cask_args appdir: '/Applications'

tap 'homebrew/versions'
tap 'caskroom/versions'

brew 'coreutils'
brew 'findutils'

brew 'zsh'

brew 'python'
brew 'python3'

brew 'wget'
brew 'openssl'
brew 'cmus'
brew 'imagemagick'
brew 'screenfetch'
brew 'ssh-copy-id'
brew 'wakeonlan'
brew 'ffmpeg'
brew 'git'
brew 'htop-osx'
brew 'nmap'
brew 'node'
brew 'sqlite'
brew 'tree'
brew 'z'

cask 'dropbox'
cask 'macdown'
cask 'shiftit'
cask 'iterm2-beta'
cask 'appcleaner'
cask 'virtualbox'
cask 'virtualbox-extension-pack'
cask 'wireshark'
cask 'dolphin'
cask 'gimp'
cask 'teamviewer'
cask 'torbrowser'
cask 'bittorrent-sync'
cask 'musicbrainz-picard'
cask 'steam'
cask 'java7'
cask 'netbeans'
cask 'telegram'
cask 'go2shell'
cask 'qlcolorcode'
cask 'qlstephen'
cask 'qlmarkdown'
cask 'quicklook-json'
cask 'quicklook-csv'
cask 'suspicious-package'
