# cask_args appdir: '/Applications'

tap 'caskroom/versions'
tap 'homebrew/versions'
tap 'caskroom/fonts'
tap 'argon/mas'
tap 'homebrew/fuse'


brew 'cmus'
brew 'p7zip'
brew 'coreutils'
brew 'ffmpeg'
brew 'findutils'
brew 'git'
brew 'git-lfs'
brew 'htop-osx'
brew 'imagemagick'
brew 'argon/mas/mas'
brew 'nmap'
brew 'node'
brew 'openssl'
brew 'python'
brew 'python3'
brew 'screenfetch'
brew 's3fs'
brew 'sqlite'
brew 'ssh-copy-id'
brew 'tree'
brew 'wakeonlan'
brew 'wget'
brew 'z'
brew 'zsh'

cask 'appcleaner'
cask 'resilio-sync'
cask 'filezilla'
cask 'firefoxdeveloperedition'
cask 'font-source-code-pro'
cask 'gimp'
cask 'google-chrome-canary'
cask 'hyperdock'
cask 'iterm2'
cask 'java'
cask 'musicbrainz-picard'
cask 'qlcolorcode'
cask 'qlmarkdown'
cask 'qlstephen'
cask 'quicklook-csv'
cask 'quicklook-json'
cask 'shiftit'
cask 'suspicious-package'
cask 'teamviewer'
cask 'torbrowser'
cask 'virtualbox'
cask 'virtualbox-extension-pack'
cask 'vlc'
cask 'wireshark'
